// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: imu_packet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IMUPacketService_SetFIFOStatus_FullMethodName        = "/protocol.IMUPacketService/SetFIFOStatus"
	IMUPacketService_GetFIFOStatus_FullMethodName        = "/protocol.IMUPacketService/GetFIFOStatus"
	IMUPacketService_GetPacketArray_FullMethodName       = "/protocol.IMUPacketService/GetPacketArray"
	IMUPacketService_GetPacketArrayStream_FullMethodName = "/protocol.IMUPacketService/GetPacketArrayStream"
	IMUPacketService_ListDev_FullMethodName              = "/protocol.IMUPacketService/ListDev"
)

// IMUPacketServiceClient is the client API for IMUPacketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMUPacketServiceClient interface {
	SetFIFOStatus(ctx context.Context, in *IMUSetFIFOStatusRequest, opts ...grpc.CallOption) (*IMUStatusResponse, error)
	GetFIFOStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IMUStatusResponse, error)
	GetPacketArray(ctx context.Context, in *IMUPacketRequest, opts ...grpc.CallOption) (*IMUPacketArrayResponse, error)
	GetPacketArrayStream(ctx context.Context, in *IMUPacketRequest, opts ...grpc.CallOption) (IMUPacketService_GetPacketArrayStreamClient, error)
	ListDev(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IMUInfoResponse, error)
}

type iMUPacketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMUPacketServiceClient(cc grpc.ClientConnInterface) IMUPacketServiceClient {
	return &iMUPacketServiceClient{cc}
}

func (c *iMUPacketServiceClient) SetFIFOStatus(ctx context.Context, in *IMUSetFIFOStatusRequest, opts ...grpc.CallOption) (*IMUStatusResponse, error) {
	out := new(IMUStatusResponse)
	err := c.cc.Invoke(ctx, IMUPacketService_SetFIFOStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMUPacketServiceClient) GetFIFOStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IMUStatusResponse, error) {
	out := new(IMUStatusResponse)
	err := c.cc.Invoke(ctx, IMUPacketService_GetFIFOStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMUPacketServiceClient) GetPacketArray(ctx context.Context, in *IMUPacketRequest, opts ...grpc.CallOption) (*IMUPacketArrayResponse, error) {
	out := new(IMUPacketArrayResponse)
	err := c.cc.Invoke(ctx, IMUPacketService_GetPacketArray_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMUPacketServiceClient) GetPacketArrayStream(ctx context.Context, in *IMUPacketRequest, opts ...grpc.CallOption) (IMUPacketService_GetPacketArrayStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &IMUPacketService_ServiceDesc.Streams[0], IMUPacketService_GetPacketArrayStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &iMUPacketServiceGetPacketArrayStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IMUPacketService_GetPacketArrayStreamClient interface {
	Recv() (*IMUPacketArrayStreamResponse, error)
	grpc.ClientStream
}

type iMUPacketServiceGetPacketArrayStreamClient struct {
	grpc.ClientStream
}

func (x *iMUPacketServiceGetPacketArrayStreamClient) Recv() (*IMUPacketArrayStreamResponse, error) {
	m := new(IMUPacketArrayStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iMUPacketServiceClient) ListDev(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IMUInfoResponse, error) {
	out := new(IMUInfoResponse)
	err := c.cc.Invoke(ctx, IMUPacketService_ListDev_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMUPacketServiceServer is the server API for IMUPacketService service.
// All implementations must embed UnimplementedIMUPacketServiceServer
// for forward compatibility
type IMUPacketServiceServer interface {
	SetFIFOStatus(context.Context, *IMUSetFIFOStatusRequest) (*IMUStatusResponse, error)
	GetFIFOStatus(context.Context, *Empty) (*IMUStatusResponse, error)
	GetPacketArray(context.Context, *IMUPacketRequest) (*IMUPacketArrayResponse, error)
	GetPacketArrayStream(*IMUPacketRequest, IMUPacketService_GetPacketArrayStreamServer) error
	ListDev(context.Context, *Empty) (*IMUInfoResponse, error)
	mustEmbedUnimplementedIMUPacketServiceServer()
}

// UnimplementedIMUPacketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIMUPacketServiceServer struct {
}

func (UnimplementedIMUPacketServiceServer) SetFIFOStatus(context.Context, *IMUSetFIFOStatusRequest) (*IMUStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFIFOStatus not implemented")
}
func (UnimplementedIMUPacketServiceServer) GetFIFOStatus(context.Context, *Empty) (*IMUStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFIFOStatus not implemented")
}
func (UnimplementedIMUPacketServiceServer) GetPacketArray(context.Context, *IMUPacketRequest) (*IMUPacketArrayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPacketArray not implemented")
}
func (UnimplementedIMUPacketServiceServer) GetPacketArrayStream(*IMUPacketRequest, IMUPacketService_GetPacketArrayStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPacketArrayStream not implemented")
}
func (UnimplementedIMUPacketServiceServer) ListDev(context.Context, *Empty) (*IMUInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDev not implemented")
}
func (UnimplementedIMUPacketServiceServer) mustEmbedUnimplementedIMUPacketServiceServer() {}

// UnsafeIMUPacketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMUPacketServiceServer will
// result in compilation errors.
type UnsafeIMUPacketServiceServer interface {
	mustEmbedUnimplementedIMUPacketServiceServer()
}

func RegisterIMUPacketServiceServer(s grpc.ServiceRegistrar, srv IMUPacketServiceServer) {
	s.RegisterService(&IMUPacketService_ServiceDesc, srv)
}

func _IMUPacketService_SetFIFOStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMUSetFIFOStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUPacketServiceServer).SetFIFOStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMUPacketService_SetFIFOStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUPacketServiceServer).SetFIFOStatus(ctx, req.(*IMUSetFIFOStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMUPacketService_GetFIFOStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUPacketServiceServer).GetFIFOStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMUPacketService_GetFIFOStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUPacketServiceServer).GetFIFOStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMUPacketService_GetPacketArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMUPacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUPacketServiceServer).GetPacketArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMUPacketService_GetPacketArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUPacketServiceServer).GetPacketArray(ctx, req.(*IMUPacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMUPacketService_GetPacketArrayStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IMUPacketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IMUPacketServiceServer).GetPacketArrayStream(m, &iMUPacketServiceGetPacketArrayStreamServer{stream})
}

type IMUPacketService_GetPacketArrayStreamServer interface {
	Send(*IMUPacketArrayStreamResponse) error
	grpc.ServerStream
}

type iMUPacketServiceGetPacketArrayStreamServer struct {
	grpc.ServerStream
}

func (x *iMUPacketServiceGetPacketArrayStreamServer) Send(m *IMUPacketArrayStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IMUPacketService_ListDev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUPacketServiceServer).ListDev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMUPacketService_ListDev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUPacketServiceServer).ListDev(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IMUPacketService_ServiceDesc is the grpc.ServiceDesc for IMUPacketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMUPacketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.IMUPacketService",
	HandlerType: (*IMUPacketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFIFOStatus",
			Handler:    _IMUPacketService_SetFIFOStatus_Handler,
		},
		{
			MethodName: "GetFIFOStatus",
			Handler:    _IMUPacketService_GetFIFOStatus_Handler,
		},
		{
			MethodName: "GetPacketArray",
			Handler:    _IMUPacketService_GetPacketArray_Handler,
		},
		{
			MethodName: "ListDev",
			Handler:    _IMUPacketService_ListDev_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPacketArrayStream",
			Handler:       _IMUPacketService_GetPacketArrayStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "imu_packet.proto",
}
