# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imu_packet_pb2 as imu__packet__pb2


class IMUPacketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetFIFOStatus = channel.unary_unary(
                '/protocol.IMUPacketService/SetFIFOStatus',
                request_serializer=imu__packet__pb2.IMUSetFIFOStatusRequest.SerializeToString,
                response_deserializer=imu__packet__pb2.IMUStatusResponse.FromString,
                )
        self.GetFIFOStatus = channel.unary_unary(
                '/protocol.IMUPacketService/GetFIFOStatus',
                request_serializer=imu__packet__pb2.Empty.SerializeToString,
                response_deserializer=imu__packet__pb2.IMUStatusResponse.FromString,
                )
        self.GetPacketArray = channel.unary_unary(
                '/protocol.IMUPacketService/GetPacketArray',
                request_serializer=imu__packet__pb2.IMUPacketRequest.SerializeToString,
                response_deserializer=imu__packet__pb2.IMUPacketArrayResponse.FromString,
                )
        self.GetPacketArrayStream = channel.unary_stream(
                '/protocol.IMUPacketService/GetPacketArrayStream',
                request_serializer=imu__packet__pb2.IMUPacketRequest.SerializeToString,
                response_deserializer=imu__packet__pb2.IMUPacketArrayStreamResponse.FromString,
                )
        self.ListDev = channel.unary_unary(
                '/protocol.IMUPacketService/ListDev',
                request_serializer=imu__packet__pb2.Empty.SerializeToString,
                response_deserializer=imu__packet__pb2.IMUInfoResponse.FromString,
                )


class IMUPacketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetFIFOStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFIFOStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPacketArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPacketArrayStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDev(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IMUPacketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetFIFOStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFIFOStatus,
                    request_deserializer=imu__packet__pb2.IMUSetFIFOStatusRequest.FromString,
                    response_serializer=imu__packet__pb2.IMUStatusResponse.SerializeToString,
            ),
            'GetFIFOStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFIFOStatus,
                    request_deserializer=imu__packet__pb2.Empty.FromString,
                    response_serializer=imu__packet__pb2.IMUStatusResponse.SerializeToString,
            ),
            'GetPacketArray': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPacketArray,
                    request_deserializer=imu__packet__pb2.IMUPacketRequest.FromString,
                    response_serializer=imu__packet__pb2.IMUPacketArrayResponse.SerializeToString,
            ),
            'GetPacketArrayStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPacketArrayStream,
                    request_deserializer=imu__packet__pb2.IMUPacketRequest.FromString,
                    response_serializer=imu__packet__pb2.IMUPacketArrayStreamResponse.SerializeToString,
            ),
            'ListDev': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDev,
                    request_deserializer=imu__packet__pb2.Empty.FromString,
                    response_serializer=imu__packet__pb2.IMUInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocol.IMUPacketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IMUPacketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetFIFOStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protocol.IMUPacketService/SetFIFOStatus',
            imu__packet__pb2.IMUSetFIFOStatusRequest.SerializeToString,
            imu__packet__pb2.IMUStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFIFOStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protocol.IMUPacketService/GetFIFOStatus',
            imu__packet__pb2.Empty.SerializeToString,
            imu__packet__pb2.IMUStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPacketArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protocol.IMUPacketService/GetPacketArray',
            imu__packet__pb2.IMUPacketRequest.SerializeToString,
            imu__packet__pb2.IMUPacketArrayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPacketArrayStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protocol.IMUPacketService/GetPacketArrayStream',
            imu__packet__pb2.IMUPacketRequest.SerializeToString,
            imu__packet__pb2.IMUPacketArrayStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDev(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protocol.IMUPacketService/ListDev',
            imu__packet__pb2.Empty.SerializeToString,
            imu__packet__pb2.IMUInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
